version: "3"
services:
    mongo:
        hostname: mongodb
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M